### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by piyushbest** [UnknownOre/EnchantShopUI#1]
U COPY MY CODES BUT U NOT CREDISLTS

SECONS

BUG ITS WORK ON POCKETMINE ON NOT WORK ON SERVER HOSTION ITS ONLY WORK ON PMMP 64 APPLICATION

**Comment by piyushbest** [comment]
AND ITS NOT MADE BY U

**Comment by UnknownOre** [comment]
What you are talking about you can look at my code way different than urs btw It's VCraftMCPE code not yours look at https://github.com/Benjiboi6578/EnchantShopUI
