### ISSUE TITLE
some bugs

### ISSUE THREAD

**Issue by LeoBdt** [UnknownOre/EnchantShopUI#12]
Hello, thanks for the update but i've found many bugs. 

1) I've set a message for "incompatible-with" in config but it still blank.
2) I can't break enchanting table un survival (it opens ui)
3) add an option to disable the thanks message.

**Comment by UnknownOre** [comment]
@LeoBdt to disable a message leave it blank like this 
thanks:
and the incompatible message is incompatible-enchantment and not incompatible-with

**Comment by LeoBdt** [comment]
yeah but incompatible-enchantment still blank.

**Comment by UnknownOre** [comment]
@LeoBdt fixed it was a typo
