### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by ManiakMCPE** [UnknownOre/EnchantShopUI#16]
### Issue description
Crash when opening shop

### Steps to reproduce the issue
Open shop

### OS and versions
* PocketMine-MP: 3.7.1

### Crashdump, backtrace or other files
04.04 02:53:09 [Server] Server thread/DEBUG #2 src/pocketmine/plugin/RegisteredListener(98): pocketmine\plugin\MethodEventExecutor->execute(UnknownOre\EnchantUI\EventListener object, pocketmine\event\player\PlayerInteractEvent object)
04.04 02:53:09 [Server] Server thread/DEBUG #1 src/pocketmine/plugin/MethodEventExecutor(38): UnknownOre\EnchantUI\EventListener->onInteract(pocketmine\event\player\PlayerInteractEvent object)
04.04 02:53:09 [Server] Server thread/DEBUG #0 plugins/EnchantShopUI-56135b8022218e3a102095a36b7451eee3a31541/src/UnknownOre/EnchantUI/EventListener(33): UnknownOre\EnchantUI\Main->listForm(pocketmine\Player object)
04.04 02:53:09 [Server] Server thread/CRITICAL Error: "Class 'UnknownOre\EnchantUI\libs\jojoe77777\FormAPI\SimpleForm' not found" (EXCEPTION) in "plugins/EnchantShopUI-56135b8022218e3a102095a36b7451eee3a31541/src/UnknownOre/EnchantUI/Main" at line 72

**Comment by UnknownOre** [comment]
download the plugin from poggit 
link https://poggit.pmmp.io/p/EnchantUI

Duplication of #14 and #10

**Comment by Amitminer** [comment]
amitminer noob
