### ISSUE TITLE
I cant add any other enchants... please fix!!

### ISSUE THREAD

**Issue by Devisits** [UnknownOre/EnchantShopUI#18]
### Issue description
- I can only add fire_protection and protection... please fix.

### Steps to reproduce the issue
1. /eshop
2. click a enchant I added

### OS and versions

* PocketMine-MP:
* PHP:

**Comment by UnknownOre** [comment]
what you mean? i can add all other pmmp enchantments it works fine

**Comment by BroCrows** [comment]
Hey Devisits, open up the file click shop.yml and change the enchants, and to add one I normally copy and paste it then change the enchants.
