### ISSUE TITLE
ERROR

### ISSUE THREAD

**Issue by jhampt** [UnknownOre/EnchantShopUI#21]
08.06 01:12:40 [Server] Server thread/INFO No new updates were found. You are using the latest version.
08.06 01:12:56 [Server] Server thread/CRITICAL Error: "Class 'UnknownOre\EnchantUI\libs\jojoe77777\FormAPI\SimpleForm' not found" (EXCEPTION) in "plugins/EnchantShopUI-master/src/UnknownOre/EnchantUI/Main" at line 74
08.06 01:12:56 [Server] Server thread/DEBUG #0 plugins/EnchantShopUI-master/src/UnknownOre/EnchantUI/Commands/ShopCommand(45): UnknownOre\EnchantUI\Main->listForm(pocketmine\Player object)
08.06 01:12:56 [Server] Server thread/DEBUG #1 src/pocketmine/command/SimpleCommandMap(270): UnknownOre\EnchantUI\Commands\ShopCommand->execute(pocketmine\Player object, string enchantui, array Array())
08.06 01:12:56 [Server] Server thread/DEBUG #2 src/pocketmine/Server(2020): pocketmine\command\SimpleCommandMap->dispatch(pocketmine\Player object, string enchantui)
08.06 01:12:56 [Server] Server thread/DEBUG #3 src/pocketmine/Player(2231): pocketmine\Server->dispatchCommand(pocketmine\Player object, string enchantui)
08.06 01:12:56 [Server] Server thread/DEBUG #4 src/pocketmine/network/mcpe/PlayerNetworkSessionAdapter(239): pocketmine\Player->chat(string /enchantui)
08.06 01:12:56 [Server] Server thread/DEBUG #5 src/pocketmine/network/mcpe/protocol/CommandRequestPacket(54): pocketmine\network\mcpe\PlayerNetworkSessionAdapter->handleCommandRequest(pocketmine\network\mcpe\protocol\CommandRequestPacket object)
08.06 01:12:56 [Server] Server thread/DEBUG #6 src/pocketmine/network/mcpe/PlayerNetworkSessionAdapter(109): pocketmine\network\mcpe\protocol\CommandRequestPacket->handle(pocketmine\network\mcpe\PlayerNetworkSessionAdapter object)
08.06 01:12:56 [Server] Server thread/DEBUG #7 src/pocketmine/network/mcpe/protocol/BatchPacket(123): pocketmine\network\mcpe\PlayerNetworkSessionAdapter->handleDataPacket(pocketmine\network\mcpe\protocol\CommandRequestPacket object)
08.06 01:12:56 [Server] Server thread/DEBUG #8 src/pocketmine/network/mcpe/PlayerNetworkSessionAdapter(109): pocketmine\network\mcpe\protocol\BatchPacket->handle(pocketmine\network\mcpe\PlayerNetworkSessionAdapter object)
08.06 01:12:56 [Server] Server thread/DEBUG #9 src/pocketmine/Player(3124): pocketmine\network\mcpe\PlayerNetworkSessionAdapter->handleDataPacket(pocketmine\network\mcpe\protocol\BatchPacket object)
08.06 01:12:56 [Server] Server thread/DEBUG #10 src/pocketmine/network/mcpe/RakLibInterface(169): pocketmine\Player->handleDataPacket(pocketmine\network\mcpe\protocol\BatchPacket object)
08.06 01:12:56 [Server] Server thread/DEBUG #11 vendor/pocketmine/raklib/src/server/ServerHandler(99): pocketmine\network\mcpe\RakLibInterface->handleEncapsulated(string 75.90.209.194 52362, raklib\protocol\EncapsulatedPacket object, integer 0)
08.06 01:12:56 [Server] Server thread/DEBUG #12 src/pocketmine/network/mcpe/RakLibInterface(109): raklib\server\ServerHandler->handlePacket()
08.06 01:12:56 [Server] Server thread/DEBUG #13 src/pocketmine/network/mcpe/RakLibInterface(99): pocketmine\network\mcpe\RakLibInterface->process()
08.06 01:12:56 [Server] Server thread/DEBUG #14 vendor/pocketmine/snooze/src/SleeperHandler(123): pocketmine\network\mcpe\RakLibInterface->pocketmine\network\mcpe\{closure}()
08.06 01:12:56 [Server] Server thread/DEBUG #15 vendor/pocketmine/snooze/src/SleeperHandler(85): pocketmine\snooze\SleeperHandler->processNotifications()
08.06 01:12:56 [Server] Server thread/DEBUG #16 src/pocketmine/Server(2339): pocketmine\snooze\SleeperHandler->sleepUntil(double 1559956376.3247)
08.06 01:12:56 [Server] Server thread/DEBUG #17 src/pocketmine/Server(2196): pocketmine\Server->tickProcessor()
08.06 01:12:56 [Server] Server thread/DEBUG #18 src/pocketmine/Server(1775): pocketmine\Server->start()
08.06 01:12:56 [Server] Server thread/DEBUG #19 src/pocketmine/PocketMine(266): pocketmine\Server->__construct(BaseClassLoader object, pocketmine\utils\MainLogger object, string /, string /plugins/)
08.06 01:12:56 [Server] Server thread/DEBUG #20 (1): require(string phar:///custom-php7.2.phar/src/pocketmine/PocketMine.php)

**Comment by UnknownOre** [comment]
download the plugin from poggit
