### ISSUE TITLE
suggestion

### ISSUE THREAD

**Issue by LeoBdt** [UnknownOre/EnchantShopUI#7]
Hello can you please add a system to avoid the enchantment silk touch + fortune ? Because it makes infinite ores.

Thanks

**Comment by LeoBdt** [comment]
Because in vanilla it's impossible

**Comment by UnknownOre** [comment]
sure

**Comment by UnknownOre** [comment]
@LeoBdt Fortune enchantment still not implemented on PMMP

**Comment by LeoBdt** [comment]
Yes it is possible with /enchant so it's implement.

**Comment by UnknownOre** [comment]
@LeoBdt  [PMMP Enchantments](https://imgur.com/H79sfzC)

**Comment by LeoBdt** [comment]
done. https://drive.google.com/folderview?id=1wlD_urWmnufeB3FH2IfMPVj4BDgYJl4d

**Comment by LeoBdt** [comment]
fortune enchantment works with your plugin too.

you just have to forbid the fact one item can have fortune + silk touch due to duplication

**Comment by LeoBdt** [comment]
??

**Comment by UnknownOre** [comment]
@LeoBdt are you using vanilla enchant or something?

**Comment by LeoBdt** [comment]
No. I'm using teaspoon plugin

**Comment by LeoBdt** [comment]
But fortune enchantment is in pmmp.

Have a look there. https://github.com/pmmp/PocketMine-MP/blob/master/src/pocketmine/item/enchantment/Enchantment.php

**Comment by LeoBdt** [comment]
Id : 18

**Comment by UnknownOre** [comment]
@LeoBdt  yeah but PMMP doesn't register it look at [TeaSpoon](https://github.com/CortexPE/TeaSpoon/blob/master/src/CortexPE/item/enchantment/Enchantment.php)

**Comment by LeoBdt** [comment]
Yeah but is it hard for you to disable silk touch and fortune on a same item? In vanilla silk touch and fortune are disable on a same tool

**Comment by UnknownOre** [comment]
however i'll add something similar to what you want

**Comment by LeoBdt** [comment]
Thanks a lot, btw your plugin is very clean and useful

**Comment by usser1976** [comment]
I would be glad about that too 🤗 without teaspoons no beacons 🤔 and with luck and silk_touch we can not use the nice plugin 😔

**Comment by UnknownOre** [comment]
Im going to add something like dont-work-with in config, but the problem is i can't find a good word for it(config) 
@LeoBdt @usser1976  any idea?

**Comment by LeoBdt** [comment]
If there's silk touch cancel the event??

**Comment by UnknownOre** [comment]
@LeoBdt 
the problem is i want a good word to replace dont-work-with
the new config will look like
name: Fire Protection
enchantment: fire_protection
price: 100
max-level: 2
dont-work-with: [luck,fortune]

**Comment by LeoBdt** [comment]
"incompatible with"

**Comment by usser1976** [comment]
incompatible with 
would fit well? I also have another nice idea 😂 an option that opens the enchantUI at the tip on enchanting table 🤔 is just an idea 😂
Greetings from Germany

**Comment by LeoBdt** [comment]
Yes it would fit well. That idea is fucking good 😂

Greetings from France
