### ISSUE TITLE
Internal Server Error using dev-27 phar

### ISSUE THREAD

**Issue by greene345** [UnknownOre/EnchantShopUI#9]
Dev #28 would not even open the UI, so I tried using Dev #27. This allowed for me to be able to open the UI, and allows for me to select the enchant and even slide to where I want the enchantment to be. Final selection yields the following error. I am currently using Pocketmine 3.6.5 and EconomyAPI dev-32. File type changed from yaml to txt since GitHub wouldn't allow yaml file upload.

[errormsg.txt](https://github.com/UnknownOre/EnchantShopUI/files/2973420/errormsg.txt)
[Shop.txt](https://github.com/UnknownOre/EnchantShopUI/files/2973421/Shop.txt)

**Comment by UnknownOre** [comment]
There is some changes in pocketmine api i'll fix it

**Comment by UnknownOre** [comment]
Durability isn't a valid enchantment use unbreaking instead

**Comment by UnknownOre** [comment]
what is #28 error message

**Comment by greene345** [comment]
> Durability isn't a valid enchantment use unbreaking instead
Changed durability to unbreaking, no other changes in the Shop.yaml. When attempting to apply Bane of Arthropods, for example, to a diamond sword, the error I get is:
[error316.txt](https://github.com/UnknownOre/EnchantShopUI/files/2974623/error316.txt)

**Comment by greene345** [comment]
> what is #28 error message
See errors from using dev28
[error316-using-dev28.txt](https://github.com/UnknownOre/EnchantShopUI/files/2974625/error316-using-dev28.txt)

**Comment by UnknownOre** [comment]
here a list of enchantments names and ids
> >PROTECTION: 0;
> >FIRE_PROTECTION: 1
> >FEATHER_FALLING: 2
> >BLAST_PROTECTION: 3
> >PROJECTILE_PROTECTION: 4
> >THORNS: 5
> >RESPIRATION: 6
> >DEPTH_STRIDER : 7
> >AQUA_AFFINITY : 8
> >SHARPNESS: 9
> >SMITE: 10
> >BANE_OF_ARTHROPODS: 11
> >KNOCKBACK: 12
> >FIRE_ASPECT: 13
> >LOOTING: 14
> >EFFICIENCY: 15
> >SILK_TOUCH: 16
> >UNBREAKING: 17
> >FORTUNE: 18
> >POWER: 19
> >PUNCH: 20
> >FLAME: 21
> >INFINITY: 22
> >LUCK_OF_THE_SEA: 23
> >LURE: 24
> >FROST_WALKER: 25
> >MENDING: 26
> >BINDING: 27
> >VANISHING: 28
> >IMPALING: 29
> >RIPTIDE: 30
> >LOYALTY: 31
> >CHANNELING: 32

**Comment by greene345** [comment]
Several enchants are still not working even after switching to numerical only. Looting, Bane , and Smite still don't work on a sword for example.

**Comment by UnknownOre** [comment]
İt gives a error or the enchantment don't work?

**Comment by greene345** [comment]
Using a totally fresh diamond sword, no enchants whatsoever, and having the Bane of Arthropods in the Shops.yaml being the following.. I typed /enchantui and selected Bane of Arthropods, a single enchant, and I get the errors in console

- name: Bane of Arthropods
  enchantment: 11
  price: 10000
  max-level: 5

[error316-using-dev28-banearth.txt](https://github.com/UnknownOre/EnchantShopUI/files/2974670/error316-using-dev28-banearth.txt)

**Comment by greene345** [comment]
I tried every single one of the enchants, and all but five of them work. The five that do not work are: 
Aqua Affinity
Bane of Arthropods
Fortune
Looting
Smite

I tried using both the id's and the names, and went through all of the enchants to see which would work.

**Comment by UnknownOre** [comment]
PocketMine-MP doesn't have those enchantments

**Comment by UnknownOre** [comment]
@greene345 [PMMP enchantments](https://imgur.com/H79sfzC)

**Comment by greene345** [comment]
The list you yourself gave me contained the ID's for the five enchants that are not working in the plugin, and if I were to use the built-in /enchant command I would be able to apply them. That tells me there is a snag/issue with this plugin. Please instead of deleting my comments could you fix the issue?

For reference since you deleted my comments, the affected enchants are:
Aqua Affinity
Bane of Arthropods
Fortune
Looting
Smite

edit: attached is the error using dev30
[dev30error318.txt](https://github.com/UnknownOre/EnchantShopUI/files/2980278/dev30error318.txt)

**Comment by greene345** [comment]
Update: for the five enchantments that were not working as above, even though they are in-game and can be accessed using the /enchant command, I found a work-around using the VanillaEnchantments plugin. Obviously I'd prefer to not have to use a second plugin to make yours work, but as a short term fix this works. https://poggit.pmmp.io/p/VanillaEnchantments

**Comment by UnknownOre** [comment]
@greene345 hmmm i couldn't access those enchantments using /enchant

**Comment by UnknownOre** [comment]
[PMMP Enchantments](https://github.com/pmmp/PocketMine-MP/blob/master/src/pocketmine/item/enchantment/Enchantment.php#L124)

**Comment by greene345** [comment]
So you can see that they're coded into pmmp, and  whether using the id or name still wasn't working.

**Comment by UnknownOre** [comment]
@greene345 PMMP doesn't register Those Enchantments you can use [TeaSpoon](https://github.com/CortexPE/TeaSpoon)

**Comment by greene345** [comment]
I am using TeaSpoon. Full list of my plugins here: https://hermopolis.duat.gg/Plugins
